# Generated by Django 2.1.7 on 2019-03-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32, verbose_name='动作组名')),
            ],
            options={
                'verbose_name': '动作组表',
                'verbose_name_plural': '动作组表',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_log_time', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='最后登录时间')),
                ('last_log_ip', models.CharField(default='127.0.0.1', max_length=32, verbose_name='最后登录ip')),
                ('log_times', models.IntegerField(default=0, verbose_name='登录次数')),
                ('status', models.SmallIntegerField(default=1, help_text='1-有效 2-停职 3-离职', verbose_name='状态')),
                ('is_sysop', models.SmallIntegerField(default=0, help_text='0-否 1-是', verbose_name='是否超级管理员')),
            ],
            options={
                'verbose_name': '管理员表',
                'verbose_name_plural': '管理员表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_time', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='发布时间')),
                ('read_times', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('last_read_time', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='最后阅读时间')),
                ('reject_reason', models.CharField(default='', max_length=50, verbose_name='驳回理由')),
                ('status', models.SmallIntegerField(default=1, help_text='1-草稿箱 2-待审核 3-待发布 4-已发布 5-已驳回', verbose_name='状态')),
                ('is_deleted', models.SmallIntegerField(default=0, help_text='0-未删除 1-已删除', verbose_name='是否已删除')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Admin', verbose_name='添加人')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'ordering': ['pub_time', 'add_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='是否已删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Article', verbose_name='文章id')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Comment', verbose_name='父评论')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Article', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_back', models.SmallIntegerField(help_text='0-未评 1-好评 2-差评', verbose_name='反馈')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Article', verbose_name='文章id')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='职位名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_deleted', models.SmallIntegerField(default=0, help_text='0-未删除 1-已删除', verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '职位表',
                'verbose_name_plural': '职位表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='路由')),
                ('action', models.CharField(max_length=32, verbose_name='名称')),
                ('type', models.CharField(max_length=8, verbose_name='请求方式')),
                ('action_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ActionGroup', verbose_name='动作组')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_log_time', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='最后登录时间')),
                ('log_times', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_log_ip', models.CharField(default='127.0.0.1', max_length=32, verbose_name='最后登录ip')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'ordering': ['-register_time'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='rights',
            field=models.ManyToManyField(blank=True, null=True, to='common.Right', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='评论者id'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='common.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='admin',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='admin',
            name='rights',
            field=models.ManyToManyField(blank=True, null=True, to='common.Right', verbose_name='权限'),
        ),
    ]
