# Generated by Django 2.1.7 on 2019-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(default='', max_length=32, verbose_name='邮箱'),
        ),
    ]
