# Generated by Django 2.1.7 on 2019-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190330_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='status',
        ),
        migrations.AddField(
            model_name='admin',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='是否已删除'),
        ),
    ]
