# Generated by Django 2.1.7 on 2019-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190330_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40, verbose_name='表名')),
                ('method', models.CharField(max_length=10, verbose_name='操作方式')),
                ('sql', models.CharField(max_length=100, verbose_name='相关')),
            ],
        ),
    ]
