# Generated by Django 2.1.7 on 2019-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='admin',
            field=models.CharField(default='', max_length=30, verbose_name='管理员姓名'),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(default='', max_length=10, verbose_name='操作方式'),
        ),
        migrations.AlterField(
            model_name='log',
            name='model',
            field=models.CharField(default='', max_length=40, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='log',
            name='sql',
            field=models.CharField(default='', max_length=100, verbose_name='相关'),
        ),
    ]
