# Generated by Django 2.1.7 on 2019-03-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190330_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='sql',
        ),
    ]
