# Generated by Django 2.1.7 on 2019-03-30 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_log_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
