# Generated by Django 2.1.7 on 2019-04-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_log_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('url', models.CharField(max_length=30, verbose_name='路径')),
                ('click_time', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_time', '-add_time'], 'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': '标签表', 'verbose_name_plural': '标签表'},
        ),
    ]
