# Generated by Django 2.1.7 on 2019-04-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_menu_parent_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='', max_length=30, verbose_name='路径'),
        ),
    ]
