# Generated by Django 2.1.7 on 2019-04-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190402_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_level',
        ),
        migrations.AddField(
            model_name='menu',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Admin', verbose_name='点击者'),
            preserve_default=False,
        ),
    ]
