# Generated by Django 2.1.7 on 2019-04-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20190403_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='', max_length=30, verbose_name='封面路径'),
        ),
    ]
