# Generated by Django 2.1.7 on 2019-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190403_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckCode',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
