# Generated by Django 2.1.7 on 2019-04-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20190406_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_deleted',
        ),
    ]
