# Generated by Django 2.1.7 on 2019-04-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20190412_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_back', models.SmallIntegerField(help_text='0-未评 1-好评 2-差评', verbose_name='反馈')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Comment', verbose_name='评论id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='用户id')),
            ],
        ),
    ]
