# Generated by Django 2.1.7 on 2019-04-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_commentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfeedback',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Article', verbose_name='文章id'),
            preserve_default=False,
        ),
    ]
