# Generated by Django 2.1.7 on 2019-04-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_commentfeedback_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentfeedback',
            name='article',
        ),
    ]
