"""
Django settings for ArticleManageSystem project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+3qf#nve+3jxpr)5b6#91y$)ek7iki#yiu6#z498byohq79@6%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'common',
]

CRONJOBS = [
    ('*/1 * * * *', 'utils.functions.dian_zan')
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'ArticleManageSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ArticleManageSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'article_publish_system',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
    }
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

UPLOAD_URL = '/uploads/'
UPLOAD_DIR = os.path.join(BASE_DIR, 'uploads')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'uploads'),
]
# 静态文件本地没有加载配置
STATIC_DIR = os.path.join(BASE_DIR, 'static')

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"

WHITE_URL = [
    ("/", "GET"),
    ("/user/login/", "GET"),
    ("/user/login/", "POST"),
    ("/user/register/", "GET"),
    ("/user/register/", "POST"),
    ("/article/", "GET"),
    ("/admin/article_i/draft/", "GET"),
    ("/admin/", "POST"),
    ("/system/position/", "POST"),
    ("/admin/outer/", "GET"),
    ("/admin/main/", "GET"),
    ("/system/position/rights/", "GET"),
    ("/admin/article_i/to_audit/", "POST"),
    ("/admin/article_i/to_audit/", "PUT"),
    ("/admin/article_i/draft/", "GET"),
    ("/admin/article_i/draft/", "PUT"),
    ("/admin/article_i/draft/", "POST"),
    ("/common/uploads/img/", "POST")
]

MENU_URL = {
    "/system/position/": "职位管理",
    "/admin/": "管理员管理",
    "/admin/article_i/add/": "添加文章",
    "/admin/article_i/to_audit/": "待审核",
    "/admin/article_i/rejected/": "已驳回",
    "/admin/article_i/to_publish/": "待发布",
    "/admin/article_i/published/": "已发布",
    "/admin/article_i/error/": "异常文章",
    "/admin/tag/": "标签列表",
    "/admin/category/": "分类列表",
    "/admin/user/": "用户列表",
    "/admin/analysis/article/": "文章分析",
    "/admin/analysis/user/": "用户分析",
    "/admin/analysis/log/": "操作日志",
    "/admin/recycle_bin/": "回收站",
}

ERROR_CHAR = [
    r'%',
    r'$',
    r'*',
    r'&',
    r'|',
    r'/',
    r'\\',
]